version: "3.8"
services:
  webserver:
    image: eduma_webserver
    ports:
      - "8000:80"
  api:
    image: eduma_api
    ports:
      - "8080:8080"
    restart: on-failure
  
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: on-failure