version: "3.8"
services:
  webserver:
    image: eduma_webserver
    ports:
      - "8000:80"
  
  couchdb:
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"